# Generated by Django 4.2 on 2023-04-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=11)),
                (
                    "family_income",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                ("birth_date", models.DateField()),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
